### ISSUE TITLE
Add links to bounties

### ISSUE THREAD

**Issue by abrkn** [dsmurrell/awesome-bitcoin-cash#13]
There are bounties for Bitcoin Cash-related projects:

- https://www.bountysource.com/issues/49027183-add-bitcoin-cash-support-to-bountysource
- https://www.bountysource.com/issues/48104292-bitcoin-cash-support

Should we add those? (I'm not affiliated with the BountySource website other than having used it)

**Comment by dsmurrell** [comment]
Good idea. Added. Modify if you want something changed.

https://github.com/dsmurrell/awesome-bitcoin-cash/commit/de23aa809f512973963c8f13d5c5b2b90496fe78

**Comment by abrkn** [comment]
Looks great
