### ISSUE TITLE
you know what's awesome? you! here's a tip

### ISSUE THREAD

**Issue by deepthawtz** [dsmurrell/awesome-bitcoin-cash#35]
@GitCash send 0.008 BCH to @dsmurrell

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/129/image.png)](https://gitcash.io/claim/dsmurrell)
@dsmurrell

**Comment by dsmurrell** [comment]
Hey @deepthawtz, thank you!

Let me know if you have any feedback for this repository.
